### ISSUE TITLE
ImportError: No module named PyQt4.QtGui

### ISSUE THREAD

**Issue by tonydm** [emresaglam/netgear-cable-modem-status-scraper#2]
I ran across this repo in my efforts to pull docsis stats from my Netgear cable modem to push into my Cacti server.  I tried unsuccessfully with HTTParty.  While I was successful using Postman to test my auth, I could not successfully auth using any of the Ruby libs available, I'm a ruby and perl coder.  I have zero python experience.  I saw your repo and thought I could take a lesson.  It looks as though your using a basic http auth approach.  So no love, no lesson learned.

I'm trying to simply run your code and fail.  I've tried a number of Python versions using docker as a dev environment.  ex. `docker run --rm -it -v "${PWD}:/code" python:3.5-buster /bin/bash`

I've tried 2.7-buster, as well as other version tags.  Always run` pip install -r requirements`.  But always get `ImportError: No module named PyQt4.QtGui`

Can you steer me in the right direction?

Thanks

**Comment by emresaglam** [comment]
Hi @tonydm You have to install PyQt4. Here is the link for that to download the sources: https://www.riverbankcomputing.com/software/pyqt/download Read the entire page since you have to build SIP before building PyQT4. 

By the way, I happened to use PyQT4 libs for no apparent reason other than first thing that came to my mind. 

The problem statement is to "render" the page. I'm using QT4 webkit to do that to "imitate" a browser render. You can also use other libs for these.

**Comment by tonydm** [comment]
Hey Emre,

Thanks for the rapid response...  I appreciate the direction.  I downloaded
the sip tarball and installed it successfully, however, I'm not able to
install the Qt4 tarball.  I don't expect a hand holding.  As I said before,
I know nothing about coding in Python.  I know perl, ruby, rails, php,
pascal, fortran, cobal, vb, and some c++.  I'm not finding any google help
and the config errors don't really make clear what I'm missing to install
Qt4.

I'm a little confused by the error "qmake: could not find a Qt installation
of '' when that's what I'm trying to do, install Qt.
And I don't understand what the qmake flag wants, the name or path/name of
the qmake binary.  When I pass only the name, it says qmake is not
executable, but it is.

Feel free to pass on any additional suggestions.  I don't expect you to
troubleshoot the foundation setup.  But appreciate any experience you can
provide.

Thanks


root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3# python configure-ng.py
Querying qmake about your Qt installation...
qmake: could not find a Qt installation of ''
Error: PyQt4 requires Qt v4.1.0 or later. Use the --qmake flag to specify
the
correct version of qmake. If you are sure you are using Qt v4 then try the
configure.py script instead of this one.
root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3#

root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3# which qmake
/usr/bin/qmake

root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3# python configure-ng.py
--qmake=qmake
Usage: python configure-ng.py [opts] [name=value] [name+=value]

configure-ng.py: error: 'qmake' is not an executable
root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3# python configure-ng.py
--qmake=/usr/bin/qmake
Querying qmake about your Qt installation...
qmake: could not find a Qt installation of ''
Error: PyQt4 requires Qt v4.1.0 or later. Use the --qmake flag to specify
the
correct version of qmake. If you are sure you are using Qt v4 then try the
configure.py script instead of this one.

root@6d6ece3d1806:/code/PyQt4_gpl_x11-4.12.3# qmake
qmake: could not find a Qt installation of ''

**Comment by tonydm** [comment]
After futzing around with trying to get Qt4 and SIP installed I revisited
my ruby code.  What was a head scratcher was that I could do a successful
query using Postman but none of the copied code examples (curl, wget, php,
basic python, etc) worked.  So copied the Temporary Headers on the request,
plugged them into my original code and vola, it worked.  This
Netgear CM500-100NAS is junk.  It would be nice to just do a SNMP query.
But I didn't want to buy another modem.  Anyway, thanks again for the time
to email with some suggestions.  Much appreciated!

Tony

These headers did the trick.

require 'httparty'

resp = HTTParty.get("http://192.168.100.1/DocsisStatus.htm", :headers => {
    "Authorization" => "Basic blahblahblahblahblahblah",
    "User-Agent" => "PostmanRuntime/7.22.0",
    "Accept" => "*/*",
    "Cache-Control" => "no-cache",
    "Postman-Token" => "438c5669-c208-44fa-8bbf-7422c4eb2773",
    "Host" => "192.168.100.1",
    "Accept-Encoding" => "gzip, deflate, br",
    "Cookie" => "XSRF_TOKEN=27730066",
    "Connection" => "keep-alive"})

**Comment by emresaglam** [comment]
You can achieve similar results with any ruby WebKit. This is not a python dependency :) I agree that most consumer grade network hardware is junk ;)
